name: CI
on: [push, pull_request]
jobs:
  build:
    name: Exist ${{ matrix.exist-version }} (JDK ${{ matrix.java-version }}) Build and Test
    strategy:
      fail-fast: false
      matrix:
        java-version: ['8', '21']
        exist-version: ['5.3.0', 'release', 'latest']
        exclude:
          - exist-version: 'latest'
            java-version: '8'
          - exist-version: '5.3.0'
            java-version: '21'            
          - exist-version: 'release'
            java-version: '21'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          cache: maven
          java-version: ${{ matrix.java-version }}
      - name: Maven Build
        run: mvn clean package -DskipTests
      - name: Test
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: mvn verify